Feature/SDL Passenger Mode
Ford-Luxoft/sdl_requirements pull request #1
Opened 2018-12-07 12:10 UTC by KhrystynaDubovyk

Is related to
https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0119-SDL-passenger-mode.md

This PR is [ready] for review.

Summary
Add API folder; add OnDriverDistraction folder with TRS, UC, accessories

CLA
### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2018-12-11 14:07 UTC, yang1070 requested changes
according to the proposal
> In addition to modifying the notification as shown above, there needs to be an addition to the policy table that feeds into that notification. This way, the OEM can update the ability to allow / disallow this with an update to their policy table.

my understanding is the parameter `lockScreenDismissalEnabled` is only added to the mobile api, not hmi api. SDL get the value of `lockScreenDismissalEnabled` from policy.

case2 (an app is not in HMI level NONE)
case 2.1
HMI -> SDL : OnDriverDistraction (state=DD_OFF)
SDL -> Apps : OnDriverDistraction (state=DD_OFF)

case 2.2
HMI -> SDL : OnDriverDistraction (state=DD_ON)
policy has lockScreenDismissalEnabled as true
SDL -> Apps : OnDriverDistraction (lockScreenDismissalEnabled=true)

case 2.3
HMI -> SDL : OnDriverDistraction (state=DD_ON)
policy has lockScreenDismissalEnabled as false
SDL -> Apps : OnDriverDistraction (lockScreenDismissalEnabled=false)

2018-12-12 10:34 UTC, KhrystynaDubovyk commented
@yang1070, please advise, 
* should we add `lockScreenDismissalEnabled` to module_config in policies (instead of HMI_API) ?
* should `lockScreenDismissalEnabled` param be settable?

2018-12-21 12:38 UTC, KhrystynaDubovyk commented
@yang1070, please see the updates
 https://github.com/Ford-Luxoft/sdl_requirements/pull/1/commits/7558b9b355fd1476403b25b42f0aefc62c56e49f
https://github.com/Ford-Luxoft/sdl_requirements/pull/1/commits/631509a8260aa56d05b9b6637ada0237d92d7953

2019-03-26 12:13 UTC, IGapchuk approved these changes

2019-05-23 10:58 UTC, closed without merging